### ISSUE TITLE
Question: systemAssertions generate a new uuid and created date on every call to get an specific occurrence.

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#220] opened 2018-05-15 05:28 UTC
A call to get the details for an occurrence return a set of unchecked system assertions (systemAssertions.unchecked) where most of those entries have a new uuid and created date every time the get API is called even for the same occurrenceId, see below call for an example (Look for "code": 10)

https://biocache.ala.org.au/ws/occurrences/794e1d5b-fc14-4b77-a21a-8e73749dc910

First call
```
...
systemAssertions": {
"unchecked": [
{
"uuid": "29386240-b68e-4e3e-8032-9469a097bc44",
"name": "stateCoordinateMismatch",
"code": 18,
"problemAsserted": false,
"qaStatus": 2,
"created": "2017-12-07T22:35:42Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
{
"uuid": "b9d404e9-2d7a-4f2d-bdd6-03204c2a641a",
"name": "unrecognisedCollectionCode",
"code": 20005,
"qaStatus": 2,
"created": "2018-05-15T15:19:50Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
{
"uuid": "5264c4e1-d7f1-4bfc-accf-51925d707a25",
"name": "invalidImageUrl",
"code": 20007,
"qaStatus": 2,
"created": "2018-05-15T15:19:50Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
{
"uuid": "7dabd5f8-e508-44d1-af79-c00a18345257",
"name": "homonymIssue",
"code": 10006,
"qaStatus": 2,
"created": "2018-05-15T15:19:50Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
{
"uuid": "7f401a16-dea2-4057-8150-18b1fbf6f443",
"name": "depthInFeet",
"code": 10,
"qaStatus": 2,
"created": "2018-05-15T15:19:50Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
...
```

Second call

```
...
"systemAssertions": {
"unchecked": [
{
"uuid": "29386240-b68e-4e3e-8032-9469a097bc44",
"name": "stateCoordinateMismatch",
"code": 18,
"problemAsserted": false,
"qaStatus": 2,
"created": "2017-12-07T22:35:42Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
{
"uuid": "7c9b9259-4f67-44bc-b58d-8a7924ba8e5a",
"name": "depthInFeet",
"code": 10,
"qaStatus": 2,
"created": "2018-05-15T15:22:38Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
{
"uuid": "189cbdb7-85cc-4476-b95a-31d4109642d6",
"name": "decimalLatLongCalculatedFromEastingNorthing",
"code": 49,
"qaStatus": 2,
"created": "2018-05-15T15:22:38Z",
"propertyNames": {
"empty": false,
"traversableAgain": true
},
"qastatusName": "2"
},
...
```

The relevant line of code that will result in those fields with fresh values (uuid and created) is below

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/d87c2f3eef40f7b46d065e48ffc44e8beee82e7c/src/main/scala/au/org/ala/biocache/Store.scala#L297

Questions: 
- Is this behaviour as per design or is it serving an old shortcoming?
- What is the purpose of returning a uuid that changes between calls?

**Comment by javier-molina** [comment] 2018-05-15 05:32
@djtfmartin  Nick suggested to have your thoughts on these questions.

**Comment by djtfmartin** [comment] 2018-06-13 15:35
its not by design. this is a bug, although im not sure if there are any downstream consequences

**Comment by djtfmartin** [comment] 2022-02-16 12:42
Closing historic issue. If this is still a problem, please reopen.

**Closed** 2022-02-16 12:51 UTC
Labels: bug, priority-low
