### ISSUE TITLE
Basis of Record assertion needs to be updated to point to the right wiki page

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#813] opened 2023-06-08 23:55 UTC
in the following record:
https://biocache-test.ala.org.au/occurrences/01620921-acd0-4b87-a9b6-d114cb364cfb
You can see that it has an assertion for basis_of_record as invalid while `occurrence` is a valid value for it according to:
https://dwc.tdwg.org/terms/#dwc:basisOfRecord

Also the the popup and the wiki link is wrong:

![Image](https://user-images.githubusercontent.com/1578598/243566548-450c8ddb-8cbb-499e-bdba-f7b17cfed71e.png)

Reported by @sadeghim

**Comment by adam-collins** [comment] 2023-06-12 04:59
This is not a problem on production. e.g. https://biocache.ala.org.au/occurrences/10b470f3-ac70-454c-b5f5-d01965a7e616

Closing.

**Comment by sadeghim** [comment] 2023-06-13 00:52
try these:
https://biocache.ala.org.au/occurrences/dbe208df-2d35-4855-aed4-a08607e33f67
https://biocache.ala.org.au/occurrences/b1b825e9-4474-4f8c-8e42-c8c71620a61d

**Comment by peggynewman** [comment] 2023-06-13 02:40
@sadeghim I think those are behaving pretty much as expected

**Comment by sadeghim** [comment] 2023-06-13 02:50
@peggynewman I still see this:
![image](https://github.com/AtlasOfLivingAustralia/biocache-service/assets/1578598/05171b8e-8af8-4c5e-b477-2ca77ba44e8d)

**Comment by peggynewman** [comment] 2023-06-13 02:52
But that's correct. In the first case a dud basis of record was provided, and in the second case no basis of record was provided. In both cases the flag is correct.

**Comment by sadeghim** [comment] 2023-06-13 02:55
Sorry to confuse you, I meant that link to wiki page is incorrect.

**Comment by peggynewman** [comment] 2023-06-13 03:10
That's true, it should be https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/BASIS_OF_RECORD_INVALID

**Comment by peggynewman** [comment] 2023-06-13 03:54
There's some confusion here. The title of the issue suggests that pipelines needs a fix to the way basis of record is processed, but I don't think that's the case. There doesn't seem to be a problem record with `occurrence` as a basis of record.

**Comment by sadeghim** [comment] 2023-06-13 04:08
Updated the title to match the issue.

**Comment by sadeghim** [comment] 2023-06-13 04:12
Also it's a bit confusing when the `basis_of_record` is empty and we show only the processed value but there is an assertion for it. Usually, we add `provided "raw_value"` to say that this value is a generated one.

check this one:
https://biocache.ala.org.au/occurrences/b1b825e9-4474-4f8c-8e42-c8c71620a61d

**Comment by peggynewman** [comment] 2023-06-14 07:27
> Usually, we add provided "raw_value"
I've never seen this? I'm not sure what you mean.
There is an assertion because there was no provided value and this is a generated one. It's typical in this system to flag an issue using an assertion and fix it in the processed value.

**Comment by sadeghim** [comment] 2023-06-14 07:34
I meant "confusing" because when you look at the page the value for that field is correct:
![image](https://github.com/AtlasOfLivingAustralia/biocache-service/assets/1578598/37765f9c-3716-48df-b8ac-21270cd98586)

But, when you see an assertion it doesn't make sense unless you know that the next step is to check the original value by pressing "original vs processed" button. 
I see it from a user's experience that they don't know that have to follow that path to figure it out. 
It's not a big problem, just a bit confusing UI (obviously, not for me).

**Comment by peggynewman** [comment] 2023-06-14 07:39
Sure. When we do a UX review it's probably something one day someone will look at.

@adam-collins we're getting off topic, but the original issue that the wiki link isn't resolved in production ... will that get fixed?

https://biocache.ala.org.au/occurrences/dbe208df-2d35-4855-aed4-a08607e33f67
https://biocache.ala.org.au/occurrences/b1b825e9-4474-4f8c-8e42-c8c71620a61d

**Comment by adam-collins** [comment] 2023-12-01 03:06
The problem is that https://biocache.ala.org.au/ws/assertions/codes is out of sync with google sheet that is used to produce https://biocache.ala.org.au/dataQuality/allCodes.

**Comment by adam-collins** [comment] 2023-12-01 03:18
A longer term solution is to 
- update biocache-service message.properties with the descriptions in the spreadsheet 
- add this description into the assertions/codes response
- change biocache-hub to only use assertions/codes

**Comment by peggynewman** [comment] 2024-03-26 07:04
In biocache-test, this record assertion is pointing to the wrong thing still: https://biocache-test.ala.org.au/occurrences/abdb05d4-e799-4cdb-b481-3f8ea6b8dcde

<img width="410" alt="image" src="https://github.com/AtlasOfLivingAustralia/biocache-service/assets/1271932/29a49c3d-3ee1-4ac8-a2a8-4d35b99788e8">

**Comment by adam-collins** [comment] 2024-03-26 22:31
Changed the ala-hub config in test and it works in test.

<img width="701" alt="image" src="https://github.com/AtlasOfLivingAustralia/biocache-service/assets/8031500/c8853f2c-aa2a-418b-9efb-e555f0da6e54">

**Closed** 2024-04-01 22:23 UTC
