### ISSUE TITLE
wrong status code returned

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#543] opened 2020-10-06 02:06 UTC
While I ran Gatling test on biocache-service, this request

`https://biocache-ws-dq-test.ala.org.au/ws/webportal/params/details/1601282603173`

returns 
```
{
    "message": "No stored query available for qid:1601282603173",
    "errorType": "Server error"
}
```

with status code `500`. Should it be `404` or something indicating resource not available?

**Comment by ansell** [comment] 2020-10-06 02:09
I think HTTP 404 fits better in that situation then HTTP 500 because it is a "Not found" case.

**Comment by brucehyslop** [comment] 2020-10-28 23:42
This is a duplicate of #542

**Closed by brucehyslop** 2020-10-28 23:42 UTC
