### ISSUE TITLE
making webservices jsonp compatible

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocache-service#16] opened 2015-01-19 05:36 UTC
webservice like the one below are not jsonp compatible. If enhanced, it will benefit applications like phylojive.
```
http://sandbox.ala.org.au/ala-hub/occurrence/legend
```

**Comment by aruizca** [comment] 2015-06-17 01:30
We should be using CORS rather than JSONP

**Comment by nickdos** [comment] 2015-08-19 06:11
Duplicate of issue #12 - closing

**Closed by nickdos** 2015-08-19 06:11 UTC
Labels: enhancement
