### ISSUE TITLE
Intermittent failures for autocomplete search in biocache-service-2.x

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#203] opened 2018-04-12 23:36 UTC
The line below produces no records
https://biocache-clustered.ala.org.au/ws/autocomplete/search?q=eucalyptus+gunnii

```
{
"searchResults": {
"startIndex": 0,
"totalRecords": 0,
"query": "eucalyptus gunnii",
"pageSize": 10,
"sort": "score",
"dir": "desc",
"results": [],
"status": "OK"
}
}
```

while this below gets 17 records
https://biocache-lb.ala.org.au/ws/autocomplete/search?q=eucalyptus+gunnii

```
{
"searchResults": {
"startIndex": 0,
"totalRecords": 17,
"query": "eucalyptus gunnii",
"pageSize": 10,
"sort": "score",
"dir": "desc",
"results": [
{
"imageCount": 0,
"commonName": [
"cider gum"
],
"idxType": "TAXON",
"nameComplete": "Eucalyptus gunnii",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"commonNameSingle": "cider gum",
"score": 7042.7983,
"highlight": "<strong>Eucalyptus gunnii</strong>",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/7635785",
"rank": "species",
"checklistsCount": 0,
"order": "Myrtales",
"author": "Hook.f.",
"isAustralian": "recorded",
"right": "581903",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SPECIES",
"left": "581899",
"genus": "Eucalyptus",
"rankId": 7000,
"parentGuid": "http://id.biodiversity.org.au/node/apni/9211705",
"name": "Eucalyptus gunnii",
"guid": "http://id.biodiversity.org.au/node/apni/7635785",
"family": "Myrtaceae",
"occCount": 1798
},
{
"imageCount": 0,
"commonName": [
"Tingiringi Gum",
"Tingaringy Gum"
],
"idxType": "TAXON",
"nameComplete": "Eucalyptus glaucescens",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"commonNameSingle": "Tingaringy Gum",
"score": 27.515688,
"highlight": "Tingaringy Gum",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/2907711",
"rank": "species",
"checklistsCount": 0,
"order": "Myrtales",
"author": "Maiden & Blakely",
"isAustralian": "recorded",
"right": "580987",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SPECIES",
"left": "580987",
"genus": "Eucalyptus",
"rankId": 7000,
"parentGuid": "http://id.biodiversity.org.au/node/apni/9211705",
"name": "Eucalyptus glaucescens",
"guid": "http://id.biodiversity.org.au/node/apni/2907711",
"family": "Myrtaceae",
"occCount": 412
},
{
"imageCount": 0,
"idxType": "TAXON",
"nameComplete": "Eucalyptus ovata var. ovata",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"score": 27.515688,
"highlight": "<strong>Eucalyptus gunnii</strong>",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/2919245",
"rank": "variety",
"checklistsCount": 0,
"order": "Myrtales",
"isAustralian": "recorded",
"right": "581612",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "VARIETY",
"left": "581612",
"genus": "Eucalyptus",
"rankId": 8010,
"name": "Eucalyptus ovata var. ovata",
"guid": "http://id.biodiversity.org.au/node/apni/2919245",
"family": "Myrtaceae",
"occCount": 3151
},
{
"imageCount": 0,
"idxType": "TAXON",
"nameComplete": "Eucalyptus gunnii subsp. divaricata",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 2,
"score": 0.012849283,
"highlight": "<strong>Eucalyptus gunnii</strong> subsp. divaricata",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/7635790",
"rank": "subspecies",
"checklistsCount": 0,
"order": "Myrtales",
"author": "(McAulay & Brett) B.M.Potts",
"isAustralian": "recorded",
"right": "581902",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SUBSPECIES",
"left": "581902",
"genus": "Eucalyptus",
"rankId": 8000,
"name": "Eucalyptus gunnii subsp. divaricata",
"guid": "http://id.biodiversity.org.au/node/apni/7635790",
"family": "Myrtaceae",
"occCount": 398
},
{
"imageCount": 0,
"idxType": "TAXON",
"nameComplete": "Eucalyptus gunnii subsp. gunnii",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"score": 0.012849283,
"highlight": "<strong>Eucalyptus gunnii</strong> subsp. gunnii",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/7634468",
"rank": "subspecies",
"checklistsCount": 0,
"order": "Myrtales",
"isAustralian": "recorded",
"right": "581900",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SUBSPECIES",
"left": "581900",
"genus": "Eucalyptus",
"rankId": 8000,
"name": "Eucalyptus gunnii subsp. gunnii",
"guid": "http://id.biodiversity.org.au/node/apni/7634468",
"family": "Myrtaceae",
"occCount": 629
},
{
"imageCount": 0,
"commonName": [
"Dargo Gum"
],
"idxType": "TAXON",
"nameComplete": "Eucalyptus perriniana",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"commonNameSingle": "Dargo Gum",
"score": 0.0032123209,
"highlight": "Dargo Gum",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/2888590",
"rank": "species",
"checklistsCount": 0,
"order": "Myrtales",
"author": "F.Muell. ex Rodway",
"isAustralian": "recorded",
"right": "582289",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SPECIES",
"left": "582289",
"genus": "Eucalyptus",
"rankId": 7000,
"parentGuid": "http://id.biodiversity.org.au/node/apni/9211705",
"name": "Eucalyptus perriniana",
"guid": "http://id.biodiversity.org.au/node/apni/2888590",
"family": "Myrtaceae",
"occCount": 698
},
{
"imageCount": 0,
"commonName": [
"Broad-leaved ribbon gum"
],
"idxType": "TAXON",
"nameComplete": "Eucalyptus dalrympleana subsp. dalrympleana",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"commonNameSingle": "Broad-leaved ribbon gum",
"score": 0.0032123209,
"highlight": "Broad-leaved ribbon gum",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/2907621",
"rank": "subspecies",
"checklistsCount": 0,
"order": "Myrtales",
"isAustralian": "recorded",
"right": "581202",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SUBSPECIES",
"left": "581202",
"genus": "Eucalyptus",
"rankId": 8000,
"name": "Eucalyptus dalrympleana subsp. dalrympleana",
"guid": "http://id.biodiversity.org.au/node/apni/2907621",
"family": "Myrtaceae",
"occCount": 5859
},
{
"imageCount": 0,
"idxType": "TAXON",
"nameComplete": "Eucalyptus mannifera subsp. mannifera",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"score": 0.0032123209,
"highlight": "<strong>Eucalyptus gunnii</strong> var. maculosa",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/2921304",
"rank": "subspecies",
"checklistsCount": 0,
"order": "Myrtales",
"isAustralian": "recorded",
"right": "583076",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SUBSPECIES",
"left": "583076",
"genus": "Eucalyptus",
"rankId": 8000,
"name": "Eucalyptus mannifera subsp. mannifera",
"guid": "http://id.biodiversity.org.au/node/apni/2921304",
"family": "Myrtaceae",
"occCount": 1737
},
{
"imageCount": 0,
"commonName": [
"Candlebark"
],
"idxType": "TAXON",
"nameComplete": "Eucalyptus rubida subsp. rubida",
"hasChildren": false,
"isExcluded": false,
"distributionsCount": 0,
"commonNameSingle": "Candlebark",
"score": 0.0032123209,
"highlight": "Candlebark",
"tracksCount": 0,
"linkIdentifier": "http://id.biodiversity.org.au/node/apni/2914288",
"rank": "subspecies",
"checklistsCount": 0,
"order": "Myrtales",
"isAustralian": "recorded",
"right": "581618",
"kingdom": "Plantae",
"phylum": "Charophyta",
"classs": "Equisetopsida",
"rawRank": "SUBSPECIES",
"left": "581618",
"genus": "Eucalyptus",
"rankId": 8000,
"name": "Eucalyptus rubida subsp. rubida",
"guid": "http://id.biodiversity.org.au/node/apni/2914288",
"family": "Myrtaceae",
"occCount": 1703
}
],
"status": "OK"
}
}
```

To be confirmed if this is only because of a different data  (nameindex, etc) been used or there is some sort of issue while processing the request that ends up in no records found.

**Comment by ansell** [comment] 2018-05-09 02:00
The same nameindex is being used:

```
biocache-b4-a.ala.org.au:~# ls -lah /data/lucene/namematching
lrwxrwxrwx 1 root root 34 Oct 26  2017 /data/lucene/namematching -> /data/lucene/namematching-20171012
```

```
aws-bws-b5-a:~# ls -lah /data/lucene/namematching
lrwxrwxrwx 1 root root 35 Mar 23 11:02 /data/lucene/namematching -> /data/lucene/namematching-20171012/
```

But a different version of ala-name-matching is in use:

```
biocache-b4-a.ala.org.au:~# ls -lah /var/lib/tomcat7/webapps/ws/WEB-INF/lib/ala-name-matching-2.4.6-SNAPSHOT.jar 
-rw-r--r-- 1 tomcat7 tomcat7 346K Oct 23  2017 /var/lib/tomcat7/webapps/ws/WEB-INF/lib/ala-name-matching-2.4.6-SNAPSHOT.jar
```

```
aws-bws-b5-a:~# ls -lah /var/lib/tomcat7/webapps-biocache-clustered.ala.org.au/ws/WEB-INF/lib/ala-name-matching-3.2-SNAPSHOT.jar 
-rw-r--r-- 1 tomcat7 tomcat7 217K May  1 23:57 /var/lib/tomcat7/webapps-biocache-clustered.ala.org.au/ws/WEB-INF/lib/ala-name-matching-3.2-SNAPSHOT.jar
```

Could be a regression between ala-name-matching-2.4.6-SNAPSHOT (not sure of the git commit behind that SNAPSHOT!) and ala-name-matching-3.2-SNAPSHOT (again, not completely sure which git commit that is!)

**Comment by javier-molina** [comment] 2018-05-10 00:05
Thanks Peter. 
@charvolant I'm guessing you are the chosen one to help with this. Can you please shed some light for us?

**Comment by charvolant** [comment] 2018-05-25 01:11
It looks like the 3.x branch is not up to date with the latest GBIF checklist libraries, although the master is. Where possible, I think the 3.x branch should be merged into master, only for the lucene library updates where possible and we make 3.2 the latest release.

**Comment by djtfmartin** [comment] 2018-06-14 18:15
this is now working as expected

**Comment by ansell** [comment] 2018-06-15 00:17
This issue is still present for me:

Expected:

https://biocache.ala.org.au/ws/autocomplete/search?q=eucalyptus+gunnii

```
{"searchResults":{"startIndex":0,"totalRecords":17,"query":"eucalyptus gunnii","pageSize":10,"sort":"score","dir":"desc","results":[{"imageCount":0,"commonName":["cider gum"],"idxType":"TAXON","nameComplete":"Eucalyptus gunnii","hasChildren":false,"isExcluded":false,"distributionsCount":0,"commonNameSingle":"cider gum","score":7042.7983,"highlight":"<strong>Eucalyptus gunnii</strong>","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/7635785","rank":"species","checklistsCount":0,"order":"Myrtales","author":"Hook.f.","isAustralian":"recorded","right":"581903","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SPECIES","left":"581899","genus":"Eucalyptus","rankId":7000,"parentGuid":"http://id.biodiversity.org.au/node/apni/9211705","name":"Eucalyptus gunnii","guid":"http://id.biodiversity.org.au/node/apni/7635785","family":"Myrtaceae","occCount":1798},{"imageCount":0,"commonName":["Tingiringi Gum","Tingaringy Gum"],"idxType":"TAXON","nameComplete":"Eucalyptus glaucescens","hasChildren":false,"isExcluded":false,"distributionsCount":0,"commonNameSingle":"Tingaringy Gum","score":27.515688,"highlight":"Tingaringy Gum","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/2907711","rank":"species","checklistsCount":0,"order":"Myrtales","author":"Maiden & Blakely","isAustralian":"recorded","right":"580987","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SPECIES","left":"580987","genus":"Eucalyptus","rankId":7000,"parentGuid":"http://id.biodiversity.org.au/node/apni/9211705","name":"Eucalyptus glaucescens","guid":"http://id.biodiversity.org.au/node/apni/2907711","family":"Myrtaceae","occCount":412},{"imageCount":0,"idxType":"TAXON","nameComplete":"Eucalyptus ovata var. ovata","hasChildren":false,"isExcluded":false,"distributionsCount":0,"score":27.515688,"highlight":"<strong>Eucalyptus gunnii</strong>","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/2919245","rank":"variety","checklistsCount":0,"order":"Myrtales","isAustralian":"recorded","right":"581612","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"VARIETY","left":"581612","genus":"Eucalyptus","rankId":8010,"name":"Eucalyptus ovata var. ovata","guid":"http://id.biodiversity.org.au/node/apni/2919245","family":"Myrtaceae","occCount":3151},{"imageCount":0,"idxType":"TAXON","nameComplete":"Eucalyptus gunnii subsp. divaricata","hasChildren":false,"isExcluded":false,"distributionsCount":2,"score":0.012849283,"highlight":"<strong>Eucalyptus gunnii</strong> subsp. divaricata","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/7635790","rank":"subspecies","checklistsCount":0,"order":"Myrtales","author":"(McAulay & Brett) B.M.Potts","isAustralian":"recorded","right":"581902","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SUBSPECIES","left":"581902","genus":"Eucalyptus","rankId":8000,"name":"Eucalyptus gunnii subsp. divaricata","guid":"http://id.biodiversity.org.au/node/apni/7635790","family":"Myrtaceae","occCount":398},{"imageCount":0,"idxType":"TAXON","nameComplete":"Eucalyptus gunnii subsp. gunnii","hasChildren":false,"isExcluded":false,"distributionsCount":0,"score":0.012849283,"highlight":"<strong>Eucalyptus gunnii</strong> subsp. gunnii","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/7634468","rank":"subspecies","checklistsCount":0,"order":"Myrtales","isAustralian":"recorded","right":"581900","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SUBSPECIES","left":"581900","genus":"Eucalyptus","rankId":8000,"name":"Eucalyptus gunnii subsp. gunnii","guid":"http://id.biodiversity.org.au/node/apni/7634468","family":"Myrtaceae","occCount":629},{"imageCount":0,"commonName":["Dargo Gum"],"idxType":"TAXON","nameComplete":"Eucalyptus perriniana","hasChildren":false,"isExcluded":false,"distributionsCount":0,"commonNameSingle":"Dargo Gum","score":0.0032123209,"highlight":"Dargo Gum","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/2888590","rank":"species","checklistsCount":0,"order":"Myrtales","author":"F.Muell. ex Rodway","isAustralian":"recorded","right":"582289","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SPECIES","left":"582289","genus":"Eucalyptus","rankId":7000,"parentGuid":"http://id.biodiversity.org.au/node/apni/9211705","name":"Eucalyptus perriniana","guid":"http://id.biodiversity.org.au/node/apni/2888590","family":"Myrtaceae","occCount":698},{"imageCount":0,"commonName":["Broad-leaved ribbon gum"],"idxType":"TAXON","nameComplete":"Eucalyptus dalrympleana subsp. dalrympleana","hasChildren":false,"isExcluded":false,"distributionsCount":0,"commonNameSingle":"Broad-leaved ribbon gum","score":0.0032123209,"highlight":"Broad-leaved ribbon gum","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/2907621","rank":"subspecies","checklistsCount":0,"order":"Myrtales","isAustralian":"recorded","right":"581202","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SUBSPECIES","left":"581202","genus":"Eucalyptus","rankId":8000,"name":"Eucalyptus dalrympleana subsp. dalrympleana","guid":"http://id.biodiversity.org.au/node/apni/2907621","family":"Myrtaceae","occCount":5860},{"imageCount":0,"idxType":"TAXON","nameComplete":"Eucalyptus mannifera subsp. mannifera","hasChildren":false,"isExcluded":false,"distributionsCount":0,"score":0.0032123209,"highlight":"<strong>Eucalyptus gunnii</strong> var. maculosa","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/2921304","rank":"subspecies","checklistsCount":0,"order":"Myrtales","isAustralian":"recorded","right":"583076","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SUBSPECIES","left":"583076","genus":"Eucalyptus","rankId":8000,"name":"Eucalyptus mannifera subsp. mannifera","guid":"http://id.biodiversity.org.au/node/apni/2921304","family":"Myrtaceae","occCount":1737},{"imageCount":0,"commonName":["Candlebark"],"idxType":"TAXON","nameComplete":"Eucalyptus rubida subsp. rubida","hasChildren":false,"isExcluded":false,"distributionsCount":0,"commonNameSingle":"Candlebark","score":0.0032123209,"highlight":"Candlebark","tracksCount":0,"linkIdentifier":"http://id.biodiversity.org.au/node/apni/2914288","rank":"subspecies","checklistsCount":0,"order":"Myrtales","isAustralian":"recorded","right":"581618","kingdom":"Plantae","phylum":"Charophyta","classs":"Equisetopsida","rawRank":"SUBSPECIES","left":"581618","genus":"Eucalyptus","rankId":8000,"name":"Eucalyptus rubida subsp. rubida","guid":"http://id.biodiversity.org.au/node/apni/2914288","family":"Myrtaceae","occCount":1703}],"status":"OK"}}
```

Actually found:

https://biocache-clustered.ala.org.au/ws/autocomplete/search?q=eucalyptus+gunnii

```
{"searchResults":{"startIndex":0,"totalRecords":17,"query":"eucalyptus gunnii","pageSize":10,"sort":"score","dir":"desc","results":[],"status":"OK"}}
```

biocache-clustered is using the latest snapshot from nexus that I redeployed this morning to update the biocache-properties settings to test the solr code. The build doesn't include the git commit in the metadata, however, it looks like the versions match the latest biocache-service commit, with ``biocache-service-2.1.2-SNAPSHOT`` and ``biocache-store-2.3.1``. Those versions match the history of either https://github.com/AtlasOfLivingAustralia/biocache-service/commit/dcb2ca14c9b64bfd68453cd2d6d9a9b8b4515d35 or its parent commit

**Comment by djtfmartin** [comment] 2018-06-15 08:52
Bizarre - i cant reproduce.  Browser caching ?

**Comment by ansell** [comment] 2018-06-16 08:46
It is still failing for me today. I also ran it directly on a server, so there couldn't be any browser caching involved. More likely intermittent for some reason if you can't reproduce:

```
$ wget https://biocache-clustered.ala.org.au/ws/autocomplete/search?q=eucalyptus+gunnii
--2018-06-16 18:27:01--  https://biocache-clustered.ala.org.au/ws/autocomplete/search?q=eucalyptus+gunnii
Resolving biocache-clustered.ala.org.au (biocache-clustered.ala.org.au)... 54.206.27.30, 52.65.191.12
Connecting to biocache-clustered.ala.org.au (biocache-clustered.ala.org.au)|54.206.27.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘search?q=eucalyptus+gunnii’

search?q=eucalyptus     [ <=>                ]     149  --.-KB/s    in 0s      

2018-06-16 18:27:02 (15.7 MB/s) - ‘search?q=eucalyptus+gunnii’ saved [149]

$ cat search\?q\=eucalyptus+gunnii 
{"searchResults":{"startIndex":0,"totalRecords":17,"query":"eucalyptus gunnii","pageSize":10,"sort":"score","dir":"desc","results":[],"status":"OK"}}
```

**Comment by ansell** [comment] 2018-06-16 08:48
Ughh, definitely intermittent, running it just now after commenting (to verify I am not seeing things)  it starts to work for me both locally and on the server. If the Solr queries are failing it should be returning an error rather than an empty set of results, if for nothing else other than to rule things out quickly.

**Comment by djtfmartin** [comment] 2018-06-16 12:57
I think its the (threaded) call to retrieve species counts thats causing the erratic behaviour.

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2.x/src/main/java/au/org/ala/biocache/service/SpeciesLookupIndexService.java#L265

**Comment by ansell** [comment] 2018-07-15 23:54
Another autocomplete search that is intermittently failing (from #252) is:

```
https://biocache-clustered.ala.org.au/ws/autocomplete/search?q=shark&fq=species_habitats%3A%22Marine%22
```

The underlying issue with ``species_habitats`` was fixed over the weekend, but now it works sometimes and sometimes silently fails with the same symptoms as ``eucalyptus gunni`` when it decides not to work.

**Comment by M-Nicholls** [comment] 2018-09-19 00:59
This is required for the AODN serving up the ALA marine data, the use it to produce a taxonomic filter on the subset of records they're interested in:

AODN portal update
Our latest development on the integration of the ALA data into the AODN Portal is available here (http://portal-sandbox.aodn.org.au/search?uuid=2852a776-cbfc-4bc8-a126-f3c036814892 ).

**Closed** 2018-09-19 15:04 UTC
Labels: bug, priority-high

**Comment by djtfmartin** [comment] 2018-09-19 15:07
This is fixed in that the results will always return. 

Occurrence and other auxiliary counts that are added to the species results are updated on a thread so these will be visible once the thread has ran on initialisation. Hence the counts might be missing after a server restart until the thread has had chance to initialise the values.  If we want to change this behaviour, i suggest we raise a separate enhancement.

**Comment by ansell** [comment] 2018-09-20 01:35
I have let AODN know to test it again
