### ISSUE TITLE
Charts and number of records not populating on 'Records' tab in Collectory

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-service#881] opened 2024-02-14 03:46 UTC
Charts and number of records are not populating on 'Records' tab in Collectory

![image](https://github.com/AtlasOfLivingAustralia/collectory/assets/90439797/deddd951-ba8b-4190-b1ed-0ad7e1096458)

Other notes:
- Doesn't appear to be caused by Images
- Looks to be an issue in biocache where no records are being returned https://biocache.ala.org.au/ws/occurrences/search?q=collectionUid:co52

Chat thread: https://atlaslivingaustralia.slack.com/archives/C03EJ7ARZQW/p1707861410669679

Raised by @rosemaryjoconnor

**Comment by adam-collins** [comment] 2024-02-14 04:14
This is the expected output when there are no records for a collection. It is not a bug. Closing this issue.

**Closed by adam-collins** 2024-02-14 04:14 UTC
