### ISSUE TITLE
Should Biocache WS support query parameters that are not URL encoded?

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-service#886] opened 2024-03-08 00:50 UTC
For example:  
`https://biocache-test.ala.org.au/occurrences/search?q=species_list_uid:dr21646&fq=decade:2020&fq=country:Australia&fq=first_loaded_date:[2023-02-07T13:00:00Z%20TO%20*]&fq=occurrence_date:[2023-02-07T13:00:00Z%20TO%20*]&sort=first_loaded_date&dir=desc&disableAllQualityFilters=true`

returns no records without errors. 

However, after we replaced `species_list_uid:dr21646` with `species_list_uid%3Ddr21646`, the url returns occurences

**Comment by adam-collins** [comment] 2024-03-08 01:58
Closing as the problem is in specieslist-webapp.
1. species_list_uid is only usable for authoritative lists. e.g. https://biocache.ala.org.au/occurrences/search?q=species_list_uid:dr947
2. species_list is what you want for non-authoritative lists. e.g. `https://biocache.ala.org.au/occurrences/search?q=species_list:dr21646`
3. lists has a matching bug that prevents uploading a list with only taxonID. See https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/299
4. when you encode the colon you break the search. It ends up doing a search on the default catch all text field, i.e. the wrong results for this example.

**Closed by adam-collins** 2024-03-08 01:58 UTC

**Comment by qifeng-bai** [comment] 2024-03-08 04:18
@adam-collins However, in the Alerts, when we subscribe a list, it does not check if it is an authoritative list or not, it always use species_list_uit to construct its query
